name: Android CI

on:
  push:
    branches: [ "develop",  "main" ]
  pull_request:
    branches: [ "develop", "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Access APY_KEY
        env:
          APOD_API_KEY: ${{ secrets.APY_KEY }}
        run: echo APY_KEY=\"$APY_KEY\" > ./local.properties
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Unit Test
      run: ./gradlew testDebugUnitTest
